### ISSUE TITLE
convert test to real pytest

### ISSUE THREAD

**Issue by bitkarrot** [lightningames/pylnbits#14]
convert tests in the [test folder](https://github.com/lightningames/pylnbits/tree/main/tests)  into real pytests (https://pytest.org)

**Comment by bitkarrot** [comment]
Add Unit Tests to wallet

**Comment by jimasuen** [comment]
> convert tests in the [test folder](https://github.com/lightningames/pylnbits/tree/main/tests) into real pytests (https://pytest.org)

Currently tackling this. Will make a pull request as soon as I'm done.

**Comment by bitkarrot** [comment]
Cool! @jimasuen what's the best way to DM you? Twitter, Nostr, Simplex?

**Comment by jimasuen** [comment]
> Cool! @jimasuen what's the best way to DM you? Twitter, Nostr, Simplex?
> If you don't mind, it would help connect us a bit quicker

Twitter (jnpunch), Telegram and Signal work great for me

**Comment by jimasuen** [comment]
I made a PR ( #166 ) for this. 

I also fixed some bugs in `user_manager.py` ( #165 ) to get `tests/test_usermanager.py` to work.

**Comment by bitkarrot** [comment]
Great, thank you for the fixes. Have been extremely swamped here so took a while to come back to review. I sent you an invite to help maintain the repo if you are interested.
