### ISSUE TITLE
New function to pay LNURLP

### ISSUE THREAD

**Issue by FelixFrei** [lightningames/pylnbits#36]

**Comment by bitkarrot** [comment]
which function? :)

**Comment by FelixFrei** [comment]
I will build one, ok?

**Comment by bitkarrot** [comment]
That sounds good. I am looking forward to it. We will also have next release of pylnbits in August, so PRs by end of July will be merged into next release v 0.0.7

**Comment by bitkarrot** [comment]
closed and merged
